name: 'Format Gherkin feature files'
description: 'Format Gherkin feature files'
inputs:
  path:
    description: 'path to feature files'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: actions/checkout@v2
      with:
        repository: OneContainer/reformat-gherkin
    - run: |
        pip install poetry
        poetry build
        pip install dist/reformat_gherkin*.whl
      shell: bash
    - run: |
        ls -al ${{ github.workspace }}
        pwd
        find ${{ github.workspace }}/${{ inputs.path }} -type f -iname '*.feature' -print | xargs reformat-gherkin --check
      shell: bash
