name: 'Format Gherkin feature files'
description: 'Format Gherkin feature files'
inputs:
  path:
    description: 'path to feature files'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - run: |
        find $PWD/${{ inputs.path }} -type f -iname '*.feature' -print | \
        xargs docker run --rm -v $PWD/${{ inputs.path }}:$PWD/${{ inputs.path }} -w $PWD/${{ inputs.path }} xl4times/reformat-gherkin --check
      shell: bash
